### ISSUE TITLE
can it run on discord bots

### ISSUE THREAD

**Issue by Mom-Assistance** [HTSTEM/DiscordBackup#2]
it would be nice if it can log everything on a discord server thru a bot in to txt files.

**Comment by hanss314** [comment]
Yes it can run on discord bots

**Comment by Mom-Assistance** [comment]
i need help with thta

**Comment by qixils** [comment]
Download the `backup.py` file, put it in a folder, create a `token.txt` in the same folder containing the backup script, then run the backup script using `python3 backup.py [guild-id-here] [output-filename]`

**Comment by hanss314** [comment]
I'll update the readme sometime. I'm working on another feature rn though

**Comment by Mom-Assistance** [comment]
Im makeing a Version to run thru my bot
