### ISSUE TITLE
Is there a restore method?

### ISSUE THREAD

**Issue by doivosevic** [HTSTEM/DiscordBackup#4]
Hey!
Great job on the archival!
It feels great that I can know the texts are saved.
Now the question: What is the difference between live.py and backup.py?
I see that they both do archiving.
Also, is it possible to restore the messages on a new server?

Thanks!

**Comment by qixils** [comment]
live.py archives messages as they're sent, backup.py does a full backup of the server

**Comment by adamthedog** [comment]
It does not support restoration, as trying to send all the messages in a server will take a long time. You'll probably be heavily ratelimited for sending so many messages.
A more viable solution would be to split the sqlite DB file into one file for each channel in the server, send each file in it's respective channel, and pin it.
